### PR TITLE
Register JS & CSS within View::EVENT_BEFORE_RENDER_TEMPLATE

### PR DESCRIPTION
**Pull request by johndwells**
This commit resolves issue #10.

### CODE REVIEW

**Comment by samstevens** [comment]
Hi - this looks to solve an issue I am experiencing too. Thanks :)

**Comment by samhibberd** [comment]
Thanks @johndwells I will get this sorted today!

**Comment by samstevens** [comment]
👍

**Comment by samhibberd** [comment]
Thanks, See 1.0.7

**Comment by johndwells** [comment]
Yay!

**Pull request closed without merging**
